django/miracle/core/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView, RedirectView

from rest_framework import routers

from . import views


urlpatterns = [
    # Examples:
    # url(r'^$', 'miracle.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='home'),
    # FIXME: replace these with forms if needed
    url(r'^contact/$', RedirectView.as_view(url='https://groups.google.com/forum/#!forum/comses-dev', permanent=False),
        name='contact'),
    url(r'^report-bug/$', RedirectView.as_view(url='https://github.com/comses/miracle/issues/new', permanent=False),
        name='report_bug'),
    url(r'^dashboard/$', views.DashboardView.as_view(), name='dashboard'),
    url(r'^radiant/(?P<path>.*)$', views.RadiantProxyView.as_view()),
    url(r'^search/$', TemplateView.as_view(template_name='search.html'), name='search'),
    # FIXME: consider merging these one-off /analysis endpoints into a single endpoint with an action parameter
    url(r'^analysis/run/$', views.RunAnalysisView.as_view(), name='run-analysis'),
    url(r'^analysis/run/status/$', views.CheckAnalysisRunStatusView.as_view(), name='check-analysis-run-status'),
    url(r'^analysis/output/share/$', views.ShareOutputView.as_view(), name='share-output'),
    url(r'^user/(?P<username>[\w.@+-]+)/activity/$', views.UserActivityView.as_view(), name='user-activity'),
    url(r'^account/profile/$', views.UserProfileView.as_view(), name='profile'),
    url(r'^projects/upload/$', views.FileUploadView.as_view(), name='upload'),
    url(r'^projects/upload/(?P<task_uuid>[0-9\-a-f]+)/$', views.FileUploadStatusView.as_view(), name='upload-status'),
    url(r'^survey/$', views.qualtrics_survey_redirect, name='survey'),
]

router = routers.DefaultRouter()
router.register(r'projects', views.ProjectViewSet, base_name='project')
router.register(r'data-group', views.DataTableGroupViewSet, base_name='data-group')
router.register(r'data-column', views.DataColumnViewSet, base_name='data-column')
router.register(r'analyses', views.AnalysisViewSet, base_name='analysis')
router.register(r'outputs', views.OutputViewSet, base_name='output')
urlpatterns += router.urls

django/miracle/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views


urlpatterns = [
    # Examples:
    # url(r'^$', 'miracle.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('social.apps.django_app.urls', namespace='social')),
    url(r'^account/login/$', auth_views.login, {'template_name': 'account/login.html'}, name='login'),
    url(r'^account/logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^account/password-reset/$', auth_views.password_reset,
        {'template_name': 'account/password-reset.html'}, name='password_reset'),
    url(r'^account/password-reset-confirm/$', auth_views.password_reset_confirm,
        {'template_name': 'account/password-reset-confirm.html'}, name='password_reset_confirm'),
    url(r'^account/password-reset-done/$', auth_views.password_reset_done,
        {'template_name': 'account/password-reset-done.html'}, name='password_reset_done'),
    url(r'^account/password-reset-complete/$', auth_views.password_reset_complete,
        {'template_name': 'account/password-reset-complete.html'}, name='password_reset_complete'),
    # django-contrib-comments URLs
    url(r'^comments/', include('django_comments.urls')),
    # fallback, core.urls will catch all other unmatched urls
    url(r'', include('miracle.core.urls', namespace='core', app_name='core')),
]

django/miracle/core/views.py
from celery.result import AsyncResult
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.utils.translation import ugettext_lazy as _
from django.views.generic import TemplateView
from extra_views import InlineFormSet, UpdateWithInlinesView
from json import dumps, loads
from rest_framework import renderers, viewsets, generics, permissions, status
from rest_framework.parsers import MultiPartParser, FormParser
from rest_framework.response import Response
from rest_framework.renderers import JSONRenderer
from rest_framework.views import APIView
from rest_framework.decorators import detail_route
from revproxy.views import ProxyView


from .models import (Project, ActivityLog, MiracleUser, DataTableGroup, DataAnalysisScript, AnalysisOutput, DataColumn,
                     AnalysisOutputFile)
from .serializers import (ProjectSerializer, DataFileSerializer, UserSerializer, DataTableGroupSerializer,
                          DataAnalysisScriptSerializer, AnalysisOutputSerializer, DataColumnSerializer,
                          ActivityLogSerializer,
                          )
from .permissions import (CanViewReadOnlyOrEditProject, CanViewReadOnlyOrEditProjectResource, )
from .tasks import run_analysis_task, run_metadata_pipeline

import logging
from os import path

logger = logging.getLogger(__name__)


class LoginRequiredMixin(object):
    @classmethod
    def as_view(cls, *args, **kwargs):
        view = super(LoginRequiredMixin, cls).as_view(*args, **kwargs)
        return login_required(view)


class RadiantProxyView(ProxyView):
    upstream = 'http://radiant:3838/base/'
    add_remote_user = True

    def get_request_headers(self):
        headers = super(RadiantProxyView, self).get_request_headers()
        logger.debug("headers: %s", headers)
        # headers['Upgrade'] = 'websocket'
        # headers['Connection'] = 'Upgrade'
        return headers

class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = 'dashboard.html'

    def get_context_data(self, **kwargs):
        context = super(DashboardView, self).get_context_data(**kwargs)
        user = self.request.user
        project_serializer = ProjectSerializer(Project.objects.viewable(user), many=True,
                                               context={'request': self.request})
        # FIXME: won't scale for many users, change to client lookup
        user_serializer = UserSerializer(User.objects.all(), many=True)
        activity_serializer = ActivityLogSerializer(ActivityLog.objects.for_user(user), many=True)
        context.update(
            activity_log_json=dumps(activity_serializer.data),
            project_list_json=dumps(project_serializer.data),
            users_json=dumps(user_serializer.data),
        )
        return context


def qualtrics_survey_redirect(request):
    username = request.user.username
    surveyUrl = "https://asu.co1.qualtrics.com/SE/?SID=SV_bpCMBE5PHiB9NaZ&UserName={0}".format(username)
    return redirect(surveyUrl)


class UserActivityView(generics.GenericAPIView):
    renderer_classes = (renderers.JSONRenderer,)
    # FIXME: need to revisit permissions
    permission_classes = (permissions.IsAuthenticated,)

    def get(self, request, username=None):
        activity_logs = ActivityLog.objects.filter(creator__username=username)
        serializer = ActivityLogSerializer(activity_logs, many=True)
        return Response(serializer.data, status=200)


class MiracleUserInline(InlineFormSet):
    model = MiracleUser
    can_delete = False
    fields = ('institution', 'user',)

    def get_object(self):
        return MiracleUser.objects.get(user=self.request.user)


class UserProfileView(LoginRequiredMixin, UpdateWithInlinesView):
    template_name = 'account/profile.html'
    model = User
    inlines = [MiracleUserInline]
    fields = ('username', 'first_name', 'last_name', 'email')
    success_url = reverse_lazy('core:profile')

    def get_object(self):
        return self.request.user


class CheckAnalysisRunStatusView(APIView):
    renderer_classes = (renderers.JSONRenderer,)
    # FIXME: need to revisit permissions
    permission_classes = (permissions.IsAuthenticated,)

    def get(self, request):
        query_params = request.query_params
        task_id = query_params.get('task_id')
        async_result = AsyncResult(task_id)
        data = {'ready': async_result.ready(), 'status': async_result.status}
        if async_result.ready():
            result = async_result.result
            if isinstance(result, Exception):
                logger.exception("raised error")
                data.update(error_message=str(result))
            else:
                # run succeeded, serialize the result
                logger.debug("async result output: type(%s) - %s", type(result), result)
                serializer = AnalysisOutputSerializer(result)
                data.update(output=serializer.data)
        # query celery task status
        return Response(data, status=200)


class ShareOutputView(APIView):
    renderer_classes = (renderers.JSONRenderer,)
    # FIXME: revisit permissions
    permission_classes = (permissions.IsAuthenticated,)

    def post(self, request):
        user = request.user
        output_id = request.data.get('id')
        email = request.data.get('email')
        message = request.data.get('message')
        logger.debug("user %s sharing output %s with [%s]: %s", user, output_id, email, message)
        return Response(status=200)


class RunAnalysisView(APIView):
    renderer_classes = (renderers.JSONRenderer,)
    # FIXME: revisit permissions
    permission_classes = (permissions.IsAuthenticated,)

    def get(self, request):
        """
        Issues a celery request to run this analysis and return a 202 status URL to poll for the status of this request.
        """
        query_params = request.query_params
        pk = int(query_params.get('pk'))
        parameters = loads(query_params.get('parameters'))
        logger.debug("running analysis id %s with parameters %s", pk, parameters)
        async_result = run_analysis_task.delay(pk, parameters, user=request.user)
        logger.debug("running analysis task with id %s", async_result.id)
        return Response({'task_id': async_result.id}, status=202)


class OutputViewSet(viewsets.ModelViewSet):
    serializer_class = AnalysisOutputSerializer
    renderer_classes = (renderers.JSONRenderer,)
    permission_classes = (CanViewReadOnlyOrEditProjectResource,)

    def get_queryset(self):
        # FIXME: replace with viewable QuerySet
        return AnalysisOutput.objects.all()

    @property
    def template_name(self):
        return 'output/{}.html'.format(self.action)

    @detail_route(methods=['get'])
    def download(self, request, pk):
        output = AnalysisOutputFile.objects.get(pk=pk)
        response = HttpResponse(output.output_file.file, content_type='application/octet-stream')
        response['Content-Disposition'] = 'attachment; filename="{}"'.format(output.basename)
        return response


class AnalysisViewSet(viewsets.ModelViewSet):
    serializer_class = DataAnalysisScriptSerializer
    renderer_classes = (renderers.TemplateHTMLRenderer, renderers.JSONRenderer)
    permission_classes = (CanViewReadOnlyOrEditProjectResource,)

    def get_queryset(self):
        # FIXME: replace with viewable QuerySet
        return DataAnalysisScript.objects.all()

    @property
    def template_name(self):
        return 'analysis/{}.html'.format(self.action)

    @detail_route(methods=['GET'])
    def download(self, request, pk):
        analysis = DataAnalysisScript.objects.get(id=pk)
        content = analysis.archived_file_contents()
        response = HttpResponse(content, content_type='application/octet-stream')
        response['Content-Disposition'] = 'attachment; filename="{}"'.format(analysis.basename)
        return response

    def retrieve(self, request, *args, **kwargs):
        response = super(AnalysisViewSet, self).retrieve(request, *args, **kwargs)
        analysis = self.get_object()
        if request.accepted_renderer.format == 'html':
            code = analysis.archived_file_contents_highlighted()
            response.data = {
                'code': code,
                'analysis': analysis
            }
        else:
            analysis_json = DataAnalysisScriptSerializer(analysis, context={'request': request})
            response.data = analysis_json.data
        return response


class DataColumnViewSet(viewsets.ModelViewSet):
    serializer_class = DataColumnSerializer
    renderer_classes = (renderers.TemplateHTMLRenderer, renderers.JSONRenderer)
    permission_classes = (CanViewReadOnlyOrEditProjectResource,)
    queryset = DataColumn.objects.all()

    def perform_update(self, serializer):
        data_column = serializer.save()
# FIXME: add modified data text to DataColumnSerializer?
        ActivityLog.objects.log_project_update(self.request.user, data_column.project,
                                               "Modified column {0}".format(data_column))


class DataTableGroupViewSet(viewsets.ModelViewSet):
    serializer_class = DataTableGroupSerializer
    renderer_classes = (renderers.TemplateHTMLRenderer, renderers.JSONRenderer)
    permission_classes = (CanViewReadOnlyOrEditProjectResource,)

    @property
    def template_name(self):
        return 'data-group/{}.html'.format(self.action)

    def retrieve(self, request, *args, **kwargs):
        response = super(DataTableGroupViewSet, self).retrieve(request, *args, **kwargs)
        data_group = response.data
        response.data['data_group_json'] = dumps(data_group)
        return response

    def get_queryset(self):

django/miracle/core/templates/base.html
{% load tags %}
{% load static from staticfiles %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'index' as index_url %}
{% url 'core:contact' as contact_url %}
{% url 'core:report_bug' as issues_url %}
{% url 'core:dashboard' as dashboard_url %}
{% url 'core:project-list' as projects_url %}
{% url 'core:survey' as survey_url %}
{% url 'core:search' as search_url %}
{% url 'core:profile' as profile_url %}

<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
{% with SELECTIZE_VERSION="0.12.3" RAVENJS_VERSION="3.7.0" HUMANE_JS_VERSION="3.2.2" BOOTSWATCH_THEME="spacelab" JQUERY_VERSION="1.12.4" BOOTSTRAP_VERSION="3.3.7" FONTAWESOME_VERSION="4.6.3" %}
    <head>
    {% block head %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>{% block title %}Digging into Data: MIRACLE{% endblock title %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% comment %}
        change bootswatch templates here
        {% endcomment %}
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootswatch/{{BOOTSTRAP_VERSION}}/{{BOOTSWATCH_THEME}}/bootstrap.min.css">
        <!-- <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/{{BOOTSTRAP_VERSION}}/css/bootstrap.min.css"> -->
        <link rel='stylesheet' href="//maxcdn.bootstrapcdn.com/font-awesome/{{FONTAWESOME_VERSION}}/css/font-awesome.min.css">
        <link rel='stylesheet' href='//cdnjs.cloudflare.com/ajax/libs/selectize.js/{{SELECTIZE_VERSION}}/css/selectize.bootstrap3.min.css'>
        <link rel='stylesheet' href='//cdnjs.cloudflare.com/ajax/libs/humane-js/{{HUMANE_JS_VERSION}}/themes/original.min.css'>
        <link rel="stylesheet" href="{% static 'css/style.css' %}" media="screen" />
        <link rel="stylesheet" href="{% static 'css/pygments.css' %}" media="screen" />
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/{{JQUERY_VERSION}}/jquery.min.js"></script>
        {% with 'js/jquery-'|add:JQUERY_VERSION|add:'.min.js' as jquery_static %}
        <script>window.jQuery || document.write('<script src="{% static jquery_static %}"><\/script>')</script>
        {% endwith %}
    {% endblock head %}
    </head>
    <body>
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        {% block header %}
            <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a href="{{ index_url }}" class="navbar-brand">DiD: Miracle</a>
                    </div>
                    <ul class='nav navbar-nav'>
                        {% if user.is_authenticated %}
                            <li class='{{ request|active_re:dashboard_url }}'><a href='{{ dashboard_url }}'><i class='fa fa-tachometer'></i> Dashboard</a></li>
                            {# <li class='{{ request|active_re:search_url }}'><a href='{{ search_url }}'><i class='fa fa-search'></i> Search</a></li> #}
                            <li class='{{ request|active_re:survey_url }}'><a target='_blank' href='{{ survey_url }}'><i class='fa fa-clipboard'></i></i> IEMSS 2016 Survey</a></li>
                        {% endif %}
                        <li class='{{ request|active_re:contact_url }}'><a target='_blank' href='{{ contact_url }}'><i class='fa fa-bell-o'></i> Contact us</a></li>
                        {# for IEMSS 2016 only #}
                        <li><a target='_blank' href='{{ issues_url }}'><i class='fa fa-bullhorn'></i> Report a bug</a></li>
                    </ul>
                    <ul class="nav navbar-nav pull-right">
                        {% if user.is_authenticated %}
                            <li class="dropdown pull-right">
                                <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                {{ user.username }}<b class="caret"></b>
                                </a>
                                <!-- Dropdown menu -->
                                <ul class="dropdown-menu">
                                    <li><a href="{{ profile_url }}"><i class="fa fa-user"></i> Profile</a></li>
                                    <li><a href="{{ logout_url }}"><i class="fa fa-sign-out"></i> Sign out</a></li>
                                </ul>
                            </li>
                        {% else %}
                            <li class='{{ request|active:login_url }}'>
                                <a href='{{ login_url }}'><i class='fa fa-sign-in'></i> Sign In</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
          </nav>
        {% endblock header %}

        <section id="content" class="container-fluid">
            <div class='alert alert-danger alert-block devserver alert-dismissable' role='alert'>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h3>Beta Service</h3>
                <i class='fa fa-exclamation-triangle fa-2x'></i> This project is still in beta and under active
                development. Any data you upload or generate on this site will not be preserved. 
            </div>
            {% block content %}
            {% endblock content %}
        </section>

        <footer id="footer" class="navbar navbar-default navbar-fixed-bottom">
            {% block footer %}
            <div class='container-fluid'>
                {% block footerlinks %}
                <ul class='nav-footer list-inline hidden-xs'>
                    <li><a href='http://www.comses.net'>Network for Computational Modeling in the Socio-ecological Sciences</a></li>
                    <li><a href='http://diggingintodata.org/awards/2013/project/mining-relationships-among-variables-large-datasets-complex-systems-miracle'>Digging into Data: MIRACLE</a>
                    <li>build: {{ TAG }}</li>
                </ul>
                {% endblock footerlinks %}
            </div>
            <div class="modal fade" id="bugModal" tabindex="-1" role="dialog" aria-labelledby="bugModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                            <h4 class="modal-title" id='bugModalLabel'>Report Bug</h4>
                        </div>
                        <div class="modal-body"></div>
                    </div><!-- /.modal-content -->
                </div><!-- /.modal-dialog -->
            </div><!-- /.modal -->
            {% endblock footer %}
        </footer>

        {% comment %}
        Place additional base JS includes here that you want available on every page load.
        {% endcomment %}
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/{{BOOTSTRAP_VERSION}}/js/bootstrap.min.js"></script>
        <script src="//cdn.ravenjs.com/{{RAVENJS_VERSION}}/raven.min.js"></script>
        <script src='//cdnjs.cloudflare.com/ajax/libs/humane-js/{{HUMANE_JS_VERSION}}/humane.min.js'></script>
 
        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='//www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-XXXXX-X','auto');ga('send','pageview');
        </script>
        <script src='{% static 'js/jquery.cookie.js' %}'></script>
        {% block javascript %}
        {% endblock javascript %}
        </body>
{% endwith %}
</html>

django/miracle/core/templates/dashboard.html
{% extends "base.html" %}

{% block content %}
<div class='row'>
    <div class='col-lg-12 col-md-12'>
        <h4><i class='fa fa-tachometer'></i> Dashboard</h4>
    </div>
</div>
<div class='row'>
    <div class='col-lg-8 col-md-8'>
        <div class='panel panel-primary'>
            <div class='panel-heading'>
                <h4 class='panel-title'><i class='fa fa-table'></i> Your Projects
                    <button class='pull-right btn btn-default btn-xs' data-bind='click: createNewProject'><i class='fa fa-plus'></i> New</button>
                </h4>
            </div>
            <div class='panel-body dynamic-content projects'>
                <div data-bind='if: projects().length'>
                <table class='table striped'>
                    <thead>
                        <th class='col-md-1'>Datasets</th>
                        <th class='col-md-3'>Name</th>
                        <th class='col-md-4'>Description</th>
                        <th class='col-md-1'>Owner</th>
                        <th class='col-md-2'>Date created</th>
                    </thead>
                    <tbody data-bind='foreach: projects'>
                    <tr>
                        <td><span class='label label-badge label-warning' data-bind='text: number_of_datasets'></span> <span class='label label-primary' data-bind='text: status'></span></td>
                        <td><a data-bind='attr: {href: url}, text: name'></a></td>
                        <td data-bind='text: description'></td>
                        <td data-bind='text: creator'></td>
                        <td data-bind='text: date_created'></td>
                    </tr>
                    </tbody>
                </table>
                </div>
                <div style='display: none;' class='alert alert-success' data-bind='visible: projects().length === 0'>
                        No available projects. <span class='btn btn-warning' data-bind='click: createNewProject'><i class='fa fa-plus'></i> Create one?</span>
                </div>
            </div>
        </div>
    </div>
    <div class='col-lg-4 col-md-4'>
        <div class='panel panel-primary'>
            <div class='panel-heading'>
                <h4 class='panel-title'><i class='fa fa-history'></i> Recent Activity</h4>
            </div>
            <div class='panel-body activitylog'>
                <div data-bind='foreach: recent_activity'>
                    <div class='row'>
                        <div class='col-md-12'>
                            <span class='label label-primary' data-bind='text: date_created'></span>
                            <span class='label label-info' data-bind='text: creator'></span> <span class='text-info' data-bind='text: message'></span>
                        </div>
                    </div>
                </div>
                <div data-bind='visible: recent_activity().length === 0' class='alert alert-info'>
                    <i class='fa fa-info-circle'></i> No recent activity.
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block javascript %}
{% include "includes/ko.js" %}
{% include "includes/csrf.js" %}
{% include "includes/validate.js" %}
{% include "project/includes/detail-form.html" %}
<script type='text/template' id='project-list'>
    <div data-bind='if: projects().length'>
        <table class='table striped'>
            <thead>
                <th class='col-md-4'>Name</th>
                <th class='col-md-4'>Description</th>
                <th class='col-md-2'>Owner</th>
                <th class='col-md-2'>Date created</th>
            </thead>
            <tbody data-bind='foreach: projects'>
            <tr>
                <td><a data-bind='attr: {href: url}, text: name'></a></td>
                <td data-bind='text: description'></td>
                <td data-bind='text: creator'></td>
                <td data-bind='text: date_created'></td>
            </tr>
            </tbody>
        </table>
    </div>
    <div data-bind='ifnot: projects().length'>
    <div class='alert alert-success'>
    No available projects. <span class='btn btn-warning' data-bind='click: createNewProject'><i class='fa fa-plus'></i> Create one?</span>
    </div>
    </div>
</script>
<div class='modal fade' data-bind='modal: activateNewProject'>
<div class='modal-dialog'>
        <div class='modal-content'>
            <div class='modal-header'>
                <h4 class='modal-title'>New project
                    <button type='button' class='close' data-dismiss='modal' aria-label='Close'><span aria-hidden='true'>&times;</span></button>
                </h4>
            </div>
            <div class='modal-body'>
                <form id='new-project-form' class='form-horizontal'>
                    <project-detail-form params='model: project'></project-detail-form>
                </form>
            </div>
            <div class='modal-footer'>
                <button type='button' class='btn btn-default' data-dismiss='modal'>Close</button>
                <button type='button' class='btn btn-primary' data-bind='click: saveProject'>Create</button>
            </div>
        </div>
    </div>
</div>
<script>
{% autoescape off %}
var projects = $.parseJSON("{{ project_list_json | escapejs}}");
var activityLog = $.parseJSON("{{ activity_log_json | escapejs }}");
{% endautoescape %}
$(function() {
    function ProjectListModel(projects, activityLog) {
        var self = this;
        var model = ko.mapping.fromJS({projects: projects, recent_activity: activityLog});
        model.project = ko.observable(new ProjectModel());
        model.activateNewProject = ko.observable(false);
        model.createNewProject = function() {
            model.project(new ProjectModel());
            model.activateNewProject(true);
        }
        model.saveProject = function() {
            if ($('#new-project-form').valid()) {
                var project = model.project();
                project.save().done(function() {
                    model.refreshActivityLog();
                    model.projects.push(project);
                });
                model.activateNewProject(false);
            }
        }
        model.refreshActivityLog = function() {
            return $.get('{% url "core:user-activity" username=request.user.username %}')
                .done(function(data) {
                    console.debug(data);
                    ko.mapping.fromJS({recent_activity: data}, model);
                })
            .fail(function(response) {
                console.debug(response);
            });
        }
        return model;
    }
    ko.applyBindings(new ProjectListModel(projects, activityLog));
    $('#new-project-form').validate();
    document.documentElement.className = "js";
});
</script>

{% endblock javascript %}

django/miracle/core/templates/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}DiD: Miracle{% endblock %}

{% block content %}
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class='panel-title'>Mining relationships among variables in large datasets from complex systems</h3>
    </div>
    <div class="panel-body">
        Social scientists have used agent-based models (ABMs) to explore the interaction and feedbacks among social
        agents and their environments. The bottom-up structure of ABMs enables simulation and investigation of
        complex systems and their emergent behavior with a high level of detail; however the stochastic nature and
        potential combinations of parameters of such models create large non-linear multidimensional “big data,”
        which are difficult to analyze using traditional statistical methods. Our proposed project seeks to address
        this challenge by developing algorithms and web-based analysis and visualization tools that provide
        automated means of discovering complex relationships among variables. The tools will enable modelers to
        easily manage, analyze, visualize, and compare their output data, and will provide stakeholders, policy
        makers and the general public with intuitive web interfaces to explore, interact with and provide feedback
        on otherwise difficult-to-understand models.
    </div>
</div>
{% endblock content %}

django/miracle/core/templates/search.html
{% extends "base.html" %}

{% block content %}
<hr>
<div class='panel panel-default'>
    <div class='panel-heading'>
        <h4>Search</h4>
    </div>
    <div class='panel-body'>
        Not implemented yet.
    </div>
</div>
{% endblock content %}