django/miracle/core/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView, RedirectView

from rest_framework import routers

from . import views


urlpatterns = [
    # Examples:
    # url(r'^$', 'miracle.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='home'),
    # FIXME: replace these with forms if needed
    url(r'^contact/$', RedirectView.as_view(url='https://groups.google.com/forum/#!forum/comses-dev', permanent=False),
        name='contact'),
    url(r'^report-bug/$', RedirectView.as_view(url='https://github.com/comses/miracle/issues/new', permanent=False),
        name='report_bug'),
    url(r'^dashboard/$', views.DashboardView.as_view(), name='dashboard'),
    url(r'^radiant/(?P<path>.*)$', views.RadiantProxyView.as_view()),
    url(r'^search/$', TemplateView.as_view(template_name='search.html'), name='search'),
    # FIXME: consider merging these one-off /analysis endpoints into a single endpoint with an action parameter
    url(r'^analysis/run/$', views.RunAnalysisView.as_view(), name='run-analysis'),
    url(r'^analysis/run/status/$', views.CheckAnalysisRunStatusView.as_view(), name='check-analysis-run-status'),
    url(r'^analysis/output/share/$', views.ShareOutputView.as_view(), name='share-output'),
    url(r'^user/(?P<username>[\w.@+-]+)/activity/$', views.UserActivityView.as_view(), name='user-activity'),
    url(r'^account/profile/$', views.UserProfileView.as_view(), name='profile'),
    url(r'^projects/upload/$', views.FileUploadView.as_view(), name='upload'),
    url(r'^projects/upload/(?P<task_uuid>[0-9\-a-f]+)/$', views.FileUploadStatusView.as_view(), name='upload-status'),
    url(r'^survey/$', views.qualtrics_survey_redirect, name='survey'),
]

router = routers.DefaultRouter()
router.register(r'projects', views.ProjectViewSet, base_name='project')
router.register(r'data-group', views.DataTableGroupViewSet, base_name='data-group')
router.register(r'data-column', views.DataColumnViewSet, base_name='data-column')
router.register(r'analyses', views.AnalysisViewSet, base_name='analysis')
router.register(r'outputs', views.OutputViewSet, base_name='output')
urlpatterns += router.urls

django/miracle/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views


urlpatterns = [
    # Examples:
    # url(r'^$', 'miracle.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('social.apps.django_app.urls', namespace='social')),
    url(r'^account/login/$', auth_views.login, {'template_name': 'account/login.html'}, name='login'),
    url(r'^account/logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^account/password-reset/$', auth_views.password_reset,
        {'template_name': 'account/password-reset.html'}, name='password_reset'),
    url(r'^account/password-reset-confirm/$', auth_views.password_reset_confirm,
        {'template_name': 'account/password-reset-confirm.html'}, name='password_reset_confirm'),
    url(r'^account/password-reset-done/$', auth_views.password_reset_done,
        {'template_name': 'account/password-reset-done.html'}, name='password_reset_done'),
    url(r'^account/password-reset-complete/$', auth_views.password_reset_complete,
        {'template_name': 'account/password-reset-complete.html'}, name='password_reset_complete'),
    # django-contrib-comments URLs
    url(r'^comments/', include('django_comments.urls')),
    # fallback, core.urls will catch all other unmatched urls
    url(r'', include('miracle.core.urls', namespace='core', app_name='core')),
]

django/miracle/core/views.py
from celery.result import AsyncResult
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.utils.translation import ugettext_lazy as _
from django.views.generic import TemplateView
from extra_views import InlineFormSet, UpdateWithInlinesView
from json import dumps, loads
from rest_framework import renderers, viewsets, generics, permissions, status
from rest_framework.parsers import MultiPartParser, FormParser
from rest_framework.response import Response
from rest_framework.renderers import JSONRenderer
from rest_framework.views import APIView
from rest_framework.decorators import detail_route
from revproxy.views import ProxyView


from .models import (Project, ActivityLog, MiracleUser, DataTableGroup, DataAnalysisScript, AnalysisOutput, DataColumn,
                     AnalysisOutputFile)
from .serializers import (ProjectSerializer, DataFileSerializer, UserSerializer, DataTableGroupSerializer,
                          DataAnalysisScriptSerializer, AnalysisOutputSerializer, DataColumnSerializer,
                          ActivityLogSerializer,
                          )
from .permissions import (CanViewReadOnlyOrEditProject, CanViewReadOnlyOrEditProjectResource, )
from .tasks import run_analysis_task, run_metadata_pipeline

import logging
from os import path

logger = logging.getLogger(__name__)


class LoginRequiredMixin(object):
    @classmethod
    def as_view(cls, *args, **kwargs):
        view = super(LoginRequiredMixin, cls).as_view(*args, **kwargs)
        return login_required(view)


class RadiantProxyView(ProxyView):
    upstream = 'http://radiant:3838/base/'
    add_remote_user = True

    def get_request_headers(self):
        headers = super(RadiantProxyView, self).get_request_headers()
        logger.debug("headers: %s", headers)
        # headers['Upgrade'] = 'websocket'
        # headers['Connection'] = 'Upgrade'
        return headers

class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = 'dashboard.html'

    def get_context_data(self, **kwargs):
        context = super(DashboardView, self).get_context_data(**kwargs)
        user = self.request.user
        project_serializer = ProjectSerializer(Project.objects.viewable(user), many=True,
                                               context={'request': self.request})
        # FIXME: won't scale for many users, change to client lookup
        user_serializer = UserSerializer(User.objects.all(), many=True)
        activity_serializer = ActivityLogSerializer(ActivityLog.objects.for_user(user), many=True)
        context.update(
            activity_log_json=dumps(activity_serializer.data),
            project_list_json=dumps(project_serializer.data),
            users_json=dumps(user_serializer.data),
        )
        return context


def qualtrics_survey_redirect(request):
    username = request.user.username
    surveyUrl = "https://asu.co1.qualtrics.com/SE/?SID=SV_bpCMBE5PHiB9NaZ&UserName={0}".format(username)
    return redirect(surveyUrl)


class UserActivityView(generics.GenericAPIView):
    renderer_classes = (renderers.JSONRenderer,)
    # FIXME: need to revisit permissions
    permission_classes = (permissions.IsAuthenticated,)

    def get(self, request, username=None):
        activity_logs = ActivityLog.objects.filter(creator__username=username)
        serializer = ActivityLogSerializer(activity_logs, many=True)
        return Response(serializer.data, status=200)


class MiracleUserInline(InlineFormSet):
    model = MiracleUser
    can_delete = False
    fields = ('institution', 'user',)

    def get_object(self):
        return MiracleUser.objects.get(user=self.request.user)


class UserProfileView(LoginRequiredMixin, UpdateWithInlinesView):
    template_name = 'account/profile.html'
    model = User
    inlines = [MiracleUserInline]
    fields = ('username', 'first_name', 'last_name', 'email')
    success_url = reverse_lazy('core:profile')

    def get_object(self):
        return self.request.user


class CheckAnalysisRunStatusView(APIView):
    renderer_classes = (renderers.JSONRenderer,)
    # FIXME: need to revisit permissions
    permission_classes = (permissions.IsAuthenticated,)

    def get(self, request):
        query_params = request.query_params
        task_id = query_params.get('task_id')
        async_result = AsyncResult(task_id)
        data = {'ready': async_result.ready(), 'status': async_result.status}
        if async_result.ready():
            result = async_result.result
            if isinstance(result, Exception):
                logger.exception("raised error")
                data.update(error_message=str(result))
            else:
                # run succeeded, serialize the result
                logger.debug("async result output: type(%s) - %s", type(result), result)
                serializer = AnalysisOutputSerializer(result)
                data.update(output=serializer.data)
        # query celery task status
        return Response(data, status=200)


class ShareOutputView(APIView):
    renderer_classes = (renderers.JSONRenderer,)
    # FIXME: revisit permissions
    permission_classes = (permissions.IsAuthenticated,)

    def post(self, request):
        user = request.user
        output_id = request.data.get('id')
        email = request.data.get('email')
        message = request.data.get('message')
        logger.debug("user %s sharing output %s with [%s]: %s", user, output_id, email, message)
        return Response(status=200)


class RunAnalysisView(APIView):
    renderer_classes = (renderers.JSONRenderer,)
    # FIXME: revisit permissions
    permission_classes = (permissions.IsAuthenticated,)

    def get(self, request):
        """
        Issues a celery request to run this analysis and return a 202 status URL to poll for the status of this request.
        """
        query_params = request.query_params
        pk = int(query_params.get('pk'))
        parameters = loads(query_params.get('parameters'))
        logger.debug("running analysis id %s with parameters %s", pk, parameters)
        async_result = run_analysis_task.delay(pk, parameters, user=request.user)
        logger.debug("running analysis task with id %s", async_result.id)
        return Response({'task_id': async_result.id}, status=202)


class OutputViewSet(viewsets.ModelViewSet):
    serializer_class = AnalysisOutputSerializer
    renderer_classes = (renderers.JSONRenderer,)
    permission_classes = (CanViewReadOnlyOrEditProjectResource,)

    def get_queryset(self):
        # FIXME: replace with viewable QuerySet
        return AnalysisOutput.objects.all()

    @property
    def template_name(self):
        return 'output/{}.html'.format(self.action)

    @detail_route(methods=['get'])
    def download(self, request, pk):
        output = AnalysisOutputFile.objects.get(pk=pk)
        response = HttpResponse(output.output_file.file, content_type='application/octet-stream')
        response['Content-Disposition'] = 'attachment; filename="{}"'.format(output.basename)
        return response


class AnalysisViewSet(viewsets.ModelViewSet):
    serializer_class = DataAnalysisScriptSerializer
    renderer_classes = (renderers.TemplateHTMLRenderer, renderers.JSONRenderer)
    permission_classes = (CanViewReadOnlyOrEditProjectResource,)

    def get_queryset(self):
        # FIXME: replace with viewable QuerySet
        return DataAnalysisScript.objects.all()

    @property
    def template_name(self):
        return 'analysis/{}.html'.format(self.action)

    @detail_route(methods=['GET'])
    def download(self, request, pk):
        analysis = DataAnalysisScript.objects.get(id=pk)
        content = analysis.archived_file_contents()
        response = HttpResponse(content, content_type='application/octet-stream')
        response['Content-Disposition'] = 'attachment; filename="{}"'.format(analysis.basename)
        return response

    def retrieve(self, request, *args, **kwargs):
        response = super(AnalysisViewSet, self).retrieve(request, *args, **kwargs)
        analysis = self.get_object()
        if request.accepted_renderer.format == 'html':
            code = analysis.archived_file_contents_highlighted()
            response.data = {
                'code': code,
                'analysis': analysis
            }
        else:
            analysis_json = DataAnalysisScriptSerializer(analysis, context={'request': request})
            response.data = analysis_json.data
        return response


class DataColumnViewSet(viewsets.ModelViewSet):
    serializer_class = DataColumnSerializer
    renderer_classes = (renderers.TemplateHTMLRenderer, renderers.JSONRenderer)
    permission_classes = (CanViewReadOnlyOrEditProjectResource,)
    queryset = DataColumn.objects.all()

    def perform_update(self, serializer):
        data_column = serializer.save()
# FIXME: add modified data text to DataColumnSerializer?
        ActivityLog.objects.log_project_update(self.request.user, data_column.project,
                                               "Modified column {0}".format(data_column))


class DataTableGroupViewSet(viewsets.ModelViewSet):
    serializer_class = DataTableGroupSerializer
    renderer_classes = (renderers.TemplateHTMLRenderer, renderers.JSONRenderer)
    permission_classes = (CanViewReadOnlyOrEditProjectResource,)

    @property
    def template_name(self):
        return 'data-group/{}.html'.format(self.action)

    def retrieve(self, request, *args, **kwargs):
        response = super(DataTableGroupViewSet, self).retrieve(request, *args, **kwargs)
        data_group = response.data
        response.data['data_group_json'] = dumps(data_group)
        return response

    def get_queryset(self):

django/miracle/core/templates/project/detail.html
{% extends "base.html" %}
{% load static %}

{% block head %}
{{ block.super }}
<link rel='stylesheet' href='//cdnjs.cloudflare.com/ajax/libs/dropzone/4.0.1/min/dropzone.min.css'>
{% endblock %}

{% block content %}
<div class='row'>
    <div class='col-md-3'>
        {# sidebar #}
        <ul class='nav nav-pills nav-stacked' role='tablist' id='project-tab'>
            <li role='presentation' class='active'>
                <a href='#overview' aria-controls='overview' role='tab' data-toggle='tab'><i class='fa fa-table'></i> Overview</a>
            </li>
            <li role='presentation'>
                <a href='#explorer' aria-controls='explorer' role='tab' data-toggle='tab'><i class='fa fa-binoculars'></i> Data explorer</a>
            </li>
            <li role='presentation'>
                <a href='#analysis' aria-controls='analysis' role='tab' data-toggle='tab'><i class='fa fa-terminal'></i> Analysis and scripts</a>
            </li>
            <li role='presentation'>
                <a href='#upload' aria-controls='upload' role='tab' data-toggle='tab'><i class='fa fa-cloud-upload'></i> Upload datasets</a>
            </li>
        </ul>
    </div>
    <div class='col-md-9'>
        <div class='panel panel-default'>
            <div class='panel-heading'>
                <h2 class='panel-title'>{{project.name}} <span class='label label-badge label-primary pull-right'>{{project.status}}</span></h2>
            </div>
            <div class='panel-body'>
                <div class='tab-content'>
                    <div role='tabpanel' class='tab-pane active' id='overview'>
                        <form class='form-horizontal' data-bind='submit: save'>
                            <project-detail-form params='model: $root'></project-detail-form>
                            <div class='well'>
                                <h3>Uploaded datasets</h3>
                                <ul class='list-group' data-bind='foreach: datasets'>
                                    <li class='list-group-item'><a data-bind='attr: {href: $data}, text: $data'></a></li>
                                </ul>
                            </div>
                            <div class='form-group'>
                                <div class='col-sm-offset-2 col-sm-8'>
                                    <button type='submit' class='btn btn-primary'><i class='fa fa-save'></i> Save</button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div role='tabpanel' class='tab-pane' id='explorer'>
                        <div class='embed-responsive embed-responsive-4by3'>
                            <div class='well'>
                                Add local radiant iframe.
                            </div>
                        </div>
                    </div>
                    <div role='tabpanel' class='tab-pane' id='analysis'>
                        {# FIXME: extract into a component (react or KO) #}
                        <div class='panel panel-primary'>
                            <div class='panel-heading'>
                                <h3 class='panel-title'><i class='fa fa-code'></i> Analyses</h3>
                            </div>
                            <div class='panel-body'>
                                <ul class='list-group' data-bind='foreach: analyses'>
                                    <li class='list-group-item'>
                                        <a class='btn btn-sm btn-info' data-bind='click: $root.runAnalysis.bind($data)'><i class='fa fa-play'></i> Run this analysis</a>
                                        <a data-bind='attr: {href: $data}, text: $data'></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class='panel panel-primary'>
                            <div class='panel-heading'>
                                <h3 class='panel-title'><i class='fa fa-database'></i> Data</h3>
                            </div>
                            <div class='panel-body'>
                                <ul class='list-group' data-bind='foreach: datasets'>
                                    <li class='list-group-item'>
                                        <a class='btn btn-sm btn-info' data-bind='attr: {href: $data}'>
                                            <i class='fa fa-download'></i> Download
                                        </a>
                                        <a data-bind='attr: {href: $data}, text: $data'></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class='panel panel-primary'>
                            <div class='panel-heading'>
                                <h3 class='panel-title'><i class='fa fa-area-chart'></i> Outputs</h3>
                            </div>
                            <div class='panel-body'>
                                Placeholder for analysis outputs (PNGs, etc)
                            </div>
                        </div>
                    </div>
                    <div role='tabpanel' class='tab-pane' id='upload'>
                        Add dataset upload for project {{project}}<br>
                        <form action="{% url 'core:upload' %}" class="dropzone" enctype="multipart/form-data" method="post" id="my-dropzone">
                            {% csrf_token %}
                            <input type="hidden" name="id" value="{{ project.id }}">
                            <div class="fallback">
                                <input name="file" type="file" multiple />
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block javascript %}
{% include "includes/ko.js" %}
{% include "includes/dropzone.js" %}
{% include "includes/csrf.js" %}
{% include "project/includes/detail-form.html" %}
<script>
$(function() {
    Dropzone.options.myDropzone = {
        paramName: "file",
    };
    var model = new ProjectModel({data: {{ project_json|safe}}} );
    model.runAnalysis = function(analysis) {
        console.debug("running analysis on: " + analysis);
    };
    ko.applyBindings(model);
    $('#project-tab a').click(function(e) {
        e.preventDefault();
        $(this).tab('show');
    });
    $('ul.nav-pills > li > a').on('shown.bs.tab', function (e) {
        var href = $(e.target).attr('href');
        var id = href.substr(1);
        window.location.hash = id;
    });
    var hash = window.location.hash;
    $('#project-tab a[href="' + hash + '"]').tab('show');
});
</script>
{% endblock %}

django/miracle/core/templates/project/list.html
{% extends "base.html" %}

{% block content %}
<div class='panel panel-default'>
    <div class='panel-heading'>
        <h4 class='panel-title'>Projects
            {% if request.user.is_authenticated %}
            <span class='btn btn-primary btn-xs' data-bind='click: createNewProject'><i class='fa fa-plus'></i> New</span>
            {% endif %}
        </h4>
    </div>
    <div class='panel-body dynamic-content'>
        <div data-bind='if: projects().length'>
            <table class='table striped'>
                <thead>
                    <th class='col-md-4'>Name</th>
                    <th class='col-md-4'>Description</th>
                    <th class='col-md-2'>Owner</th>
                    <th class='col-md-2'>Date created</th>
                </thead>
                <tbody data-bind='foreach: projects'>
                    <tr>
                        <td><a data-bind='attr: {href: detail_url}, text: name'></a></td>
                        <td data-bind='text: description'></td>
                        <td data-bind='text: creator'></td>
                        <td data-bind='text: date_created'></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div data-bind='ifnot: projects().length'>
            <div class='alert alert-success'>
                No available projects. <span class='btn btn-warning' data-bind='click: createNewProject'><i class='fa fa-plus'></i> Create one?</span>
            </div>
        </div>
    </div>
</div>
{% endblock content %}
{% block javascript %}
{% include "includes/ko.js" %}
{% include "project/includes/detail-form.html" %}
<div class='modal fade' data-bind='modal: activateNewProject'>
<div class='modal-dialog'>
        <div class='modal-content'>
            <div class='modal-header'>
                <h4 class='modal-title'>New project</h4>
                <button type='button' class='close' data-dismiss='modal' aria-label='Close'><span aria-hidden='true'>&times;</span></button>
            </div>
            <div class='modal-body'>
                <form class='form-horizontal'>
                    <project-detail-form params='model: project'></project-detail-form>
                </form>
            </div>
            <div class='modal-footer'>
                <button type='button' class='btn btn-default' data-dismiss='modal'>Close</button>
                <button type='button' class='btn btn-primary' data-bind='click: saveProject'>Create</button>
            </div>
        </div>
    </div>
</div>
<script>
$(function() {
    function ProjectListModel(projectArray) {
        var self = this;
        var model = ko.mapping.fromJS({projects: projectArray});
        model.project = ko.observable(new ProjectModel());
        model.activateNewProject = ko.observable(false);
        model.createNewProject = function() {
            model.project(new ProjectModel());
            model.activateNewProject(true);
        }
        model.saveProject = function() {
            model.project().save();
            model.activateNewProject(false);
        }
        return model;
    }
    {% comment "initialize project list"%} {% endcomment %}
    $.getJSON("{% url 'core:project-list' format='json' %}")
        .done(function(data) {
            console.debug("SUCCESS");
            ko.applyBindings(new ProjectListModel(data));
            document.documentElement.className = "js";
        }).fail(function() {
            console.debug("FAIL");
        });

});
</script>

{% endblock javascript %}